### ISSUE TITLE
Getting error C2653: 'WeifenLuo': is not a class or namespace name after upgrading from 2.5 to 2.14

### ISSUE THREAD

**Issue by MtnViewJohn** [dockpanelsuite/dockpanelsuite#485]
I have a C++/CLI winforms application that was working fine under DPS 2.5.0. I want to try the newer themes and bug fixes, so I am trying to upgrade my solution to DPS 2.14. I removed the old WinFormsUI project and added the new WinFormsUI project. Now the compiler cannot resolve the WeifenLuo namespace or access anything below it. Intellisense seems to be aware of the whole DPS namespace, but not the compiler. What do I need to do to switch over to a new version of DPS?

**Comment by lextm** [comment]
I assume your project still targets .NET Framework 2.0/3.0.

Now this library requires .NET Framework 3.5 or .NET Framework 4.0 and above,

https://github.com/dockpanelsuite/dockpanelsuite/blob/master/.nuget/DockPanelSuite.nuspec#L151

**Comment by MtnViewJohn** [comment]
It targets .NET 4.5. I did solve the problem by right-clicking my main project (the one that can't see the new DPS code) and selecting 'Add Reference...'. From this dialog I added references to WinFormsUI (and a theme). Now it all works (except for API changes that I have to fix).
